name: Cron Jobs Workflow

on:
    schedule:
        - cron: '*/2 * * * *'
2
jobs:
    cron-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Cron job step
              run: |
                echo "This is a cron job workflow."
                echo "It runs every 2 minutes."